# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Find-Duplicates
version:      1.00
version_from: lib/File/Find/Duplicates.pm
installdirs:  site
requires:
    Digest::MD5:                   2
    File::Temp:                    0.12
    Test::More:                    0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
